pipeline {
    agent any

    stages {
        stage('Init Stage') {
            steps {
                dir('jenkins') {
                    sh 'terraform init'
                }
            }
        }

        stage('Plan Stage') {
            steps {
                dir('jenkins') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Apply Stage') {
            steps {
                dir('jenkins') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
