pipeline {
    agent any

    stages {
        // stage('clone') {
        //     steps {
        //       // git branch: 'main', url: 'https://github.com/CloudTechDevOps/Terraform_CICD.git'
        //     }
        // }
        stage('init stage') {
            steps {
                sh 'terraform init'
            }
        }
         stage('plan stage') {
            steps {
                sh 'terraform plan'
            }
        }
         stage('apply stage') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}